export class VideoError extends Error {
  constructor(public code: string, message: string) {
    super(message);
    this.name = 'VideoError';
  }
}

export const ErrorCodes = {
  INVALID_VIDEO: 'INVALID_VIDEO',
  UNSUPPORTED_FORMAT: 'UNSUPPORTED_FORMAT',
  UPLOAD_TOO_LARGE: 'UPLOAD_TOO_LARGE',
  DISK_SPACE_LOW: 'DISK_SPACE_LOW',
  FFMPEG_NOT_FOUND: 'FFMPEG_NOT_FOUND',
  FFPROBE_NOT_FOUND: 'FFPROBE_NOT_FOUND',
  TRANSCRIPTION_FAILED: 'TRANSCRIPTION_FAILED',
  GEMINI_API_ERROR: 'GEMINI_API_ERROR',
  ANALYSIS_FAILED: 'ANALYSIS_FAILED',
  RENDER_FAILED: 'RENDER_FAILED',
  CAPTION_RENDER_FAILED: 'CAPTION_RENDER_FAILED',
  FILE_NOT_FOUND: 'FILE_NOT_FOUND'
} as const;
